// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819153830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Events.ShiftRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("ShiftRole");
                });

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.OwnsOne("Domain.Events.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LocationStreet");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsMany("Domain.Events.Shift", "Shifts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsCancelled")
                                .HasColumnType("bit");

                            b1.Property<DateOnly>("ShiftDate")
                                .HasColumnType("date");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("EventId");

                            b1.ToTable("Shift");

                            b1.WithOwner()
                                .HasForeignKey("EventId");

                            b1.OwnsMany("Domain.Events.ShiftRoleAssignment", "RoleAssignments", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("MaxVolunteers")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("RoleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ShiftId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RoleId");

                                    b2.HasIndex("ShiftId");

                                    b2.ToTable("ShiftRoleAssignment");

                                    b2.HasOne("Domain.Events.ShiftRole", "Role")
                                        .WithMany()
                                        .HasForeignKey("RoleId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("ShiftId");

                                    b2.Navigation("Role");
                                });

                            b1.Navigation("RoleAssignments");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Domain.Events.ShiftRole", b =>
                {
                    b.HasOne("Domain.Events.Event", null)
                        .WithMany("ShiftRoles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.Navigation("ShiftRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
